### ISSUE TITLE
How to set the width of the menu?

### ISSUE THREAD

**Issue by Tolu-Mals** [alessiocancian/react-native-side-menu#12]
I found out that I can set the size of the side menu using `openMenuOffset`, however I noticed that when the app starts in landscape mode, the same values renders different width sizes. Is there another way to set the width of the menu.

**Comment by yuanAIhan** [comment]
> 

Do you know how to close the menu through a button in menu page?

**Comment by yuanAIhan** [comment]
> I found out that I can set the size of the side menu using `openMenuOffset`, however I noticed that when the app starts in landscape mode, the same values renders different width sizes. Is there another way to set the width of the menu.

openMenuOffset={width} ?

**Comment by Tolu-Mals** [comment]
Yeah, thanks I figured it out. I had to modify the class a bit to get it working like I wanted though.
